// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type Options,
  urlSearchParamsBodySerializer,
} from "./client";
import type {
  AuthGoogleAuthGoogleGetData,
  AuthGoogleAuthGoogleGetError,
  AuthGoogleAuthGoogleGetResponse,
  CreateUserQuestionUserQuestionsPostData,
  CreateUserQuestionUserQuestionsPostError,
  CreateUserQuestionUserQuestionsPostResponse,
  GetCategoriesCategoriesGetError,
  GetCategoriesCategoriesGetResponse,
  GetEventEventsIdGetData,
  GetEventEventsIdGetError,
  GetEventEventsIdGetResponse,
  GetEventsEventsGetData,
  GetEventsEventsGetError,
  GetEventsEventsGetResponse,
  GetUserAuthSessionGetData,
  GetUserAuthSessionGetError,
  GetUserAuthSessionGetResponse,
  GetUserQuestionsUserQuestionsGetData,
  GetUserQuestionsUserQuestionsGetError,
  GetUserQuestionsUserQuestionsGetResponse,
  GetUserQuestionUserQuestionsIdGetData,
  GetUserQuestionUserQuestionsIdGetError,
  GetUserQuestionUserQuestionsIdGetResponse,
  LogInAuthLoginPostData,
  LogInAuthLoginPostError,
  LogInAuthLoginPostResponse,
  LoginGoogleAuthLoginGoogleGetError,
  LoginGoogleAuthLoginGoogleGetResponse,
  LogoutAuthLogoutGetError,
  LogoutAuthLogoutGetResponse,
  SignUpAuthSignupPostData,
  SignUpAuthSignupPostError,
  SignUpAuthSignupPostResponse,
  UpdateProfileProfilePutData,
  UpdateProfileProfilePutError,
  UpdateProfileProfilePutResponse,
} from "./types.gen";

export const client = createClient(createConfig());

/**
 * Sign Up
 */
export const signUpAuthSignupPost = <ThrowOnError extends boolean = false>(
  options: Options<SignUpAuthSignupPostData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    SignUpAuthSignupPostResponse,
    SignUpAuthSignupPostError,
    ThrowOnError
  >({
    ...options,
    url: "/auth/signup",
  });
};

/**
 * Log In
 */
export const logInAuthLoginPost = <ThrowOnError extends boolean = false>(
  options: Options<LogInAuthLoginPostData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    LogInAuthLoginPostResponse,
    LogInAuthLoginPostError,
    ThrowOnError
  >({
    ...options,
    ...urlSearchParamsBodySerializer,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options?.headers,
    },
    url: "/auth/login",
  });
};

/**
 * Login Google
 */
export const loginGoogleAuthLoginGoogleGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    LoginGoogleAuthLoginGoogleGetResponse,
    LoginGoogleAuthLoginGoogleGetError,
    ThrowOnError
  >({
    ...options,
    url: "/auth/login/google",
  });
};

/**
 * Auth Google
 */
export const authGoogleAuthGoogleGet = <ThrowOnError extends boolean = false>(
  options: Options<AuthGoogleAuthGoogleGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    AuthGoogleAuthGoogleGetResponse,
    AuthGoogleAuthGoogleGetError,
    ThrowOnError
  >({
    ...options,
    url: "/auth/google",
  });
};

/**
 * Get User
 */
export const getUserAuthSessionGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetUserAuthSessionGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetUserAuthSessionGetResponse,
    GetUserAuthSessionGetError,
    ThrowOnError
  >({
    ...options,
    url: "/auth/session",
  });
};

/**
 * Logout
 */
export const logoutAuthLogoutGet = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    LogoutAuthLogoutGetResponse,
    LogoutAuthLogoutGetError,
    ThrowOnError
  >({
    ...options,
    url: "/auth/logout",
  });
};

/**
 * Get Categories
 */
export const getCategoriesCategoriesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetCategoriesCategoriesGetResponse,
    GetCategoriesCategoriesGetError,
    ThrowOnError
  >({
    ...options,
    url: "/categories/",
  });
};

/**
 * Update Profile
 */
export const updateProfileProfilePut = <ThrowOnError extends boolean = false>(
  options: Options<UpdateProfileProfilePutData, ThrowOnError>,
) => {
  return (options?.client ?? client).put<
    UpdateProfileProfilePutResponse,
    UpdateProfileProfilePutError,
    ThrowOnError
  >({
    ...options,
    url: "/profile/",
  });
};

/**
 * Get Events
 */
export const getEventsEventsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetEventsEventsGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetEventsEventsGetResponse,
    GetEventsEventsGetError,
    ThrowOnError
  >({
    ...options,
    url: "/events/",
  });
};

/**
 * Get Event
 */
export const getEventEventsIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetEventEventsIdGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetEventEventsIdGetResponse,
    GetEventEventsIdGetError,
    ThrowOnError
  >({
    ...options,
    url: "/events/:id",
  });
};

/**
 * Get User Questions
 */
export const getUserQuestionsUserQuestionsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetUserQuestionsUserQuestionsGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetUserQuestionsUserQuestionsGetResponse,
    GetUserQuestionsUserQuestionsGetError,
    ThrowOnError
  >({
    ...options,
    url: "/user-questions/",
  });
};

/**
 * Create User Question
 */
export const createUserQuestionUserQuestionsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateUserQuestionUserQuestionsPostData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreateUserQuestionUserQuestionsPostResponse,
    CreateUserQuestionUserQuestionsPostError,
    ThrowOnError
  >({
    ...options,
    url: "/user-questions/",
  });
};

/**
 * Get User Question
 */
export const getUserQuestionUserQuestionsIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetUserQuestionUserQuestionsIdGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetUserQuestionUserQuestionsIdGetResponse,
    GetUserQuestionUserQuestionsIdGetError,
    ThrowOnError
  >({
    ...options,
    url: "/user-questions/:id",
  });
};
