// This file is auto-generated by @hey-api/openapi-ts

export type Body_log_in_auth_login_post = {
  grant_type?: string | null;
  username: string;
  password: string;
  scope?: string;
  client_id?: string | null;
  client_secret?: string | null;
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type SignUpData = {
  email: string;
  password: string;
};

export type Token = {
  access_token: string;
  token_type: string;
  user: UserPublic;
};

export type UserPublic = {
  id: number;
  email: string;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type SignUpAuthSignupPostData = {
  body: SignUpData;
};

export type SignUpAuthSignupPostResponse = unknown;

export type SignUpAuthSignupPostError = HTTPValidationError;

export type LogInAuthLoginPostData = {
  body: Body_log_in_auth_login_post;
};

export type LogInAuthLoginPostResponse = Token;

export type LogInAuthLoginPostError = HTTPValidationError;

export type LoginGoogleAuthLoginGoogleGetResponse = unknown;

export type LoginGoogleAuthLoginGoogleGetError = unknown;

export type AuthGoogleAuthGoogleGetData = {
  query: {
    code: string;
  };
};

export type AuthGoogleAuthGoogleGetResponse = unknown;

export type AuthGoogleAuthGoogleGetError = HTTPValidationError;

export type GetUserAuthSessionGetData = unknown;

export type GetUserAuthSessionGetResponse = UserPublic;

export type GetUserAuthSessionGetError = HTTPValidationError;

export type LogoutAuthLogoutGetResponse = unknown;

export type LogoutAuthLogoutGetError = unknown;
