import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";

import Navbar from "@/components/navigation/navbar";
import { cn } from "@/lib/utils";

import "./globals.css";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <main className="container flex min-h-screen min-w-full flex-col justify-between px-8 py-4 md:px-20">
          {children}
        </main>
      </body>
    </html>
  );
}
