"""add_daily_prac_strs

Revision ID: 0558471914c6
Revises: 0486b458645b
Create Date: 2024-11-13 08:10:48.315722

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0558471914c6"
down_revision: Union[str, None] = "0486b458645b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "daily_practice", sa.Column("practice_title", sa.String(), nullable=False)
    )
    op.add_column(
        "daily_practice", sa.Column("practice_intro", sa.String(), nullable=False)
    )
    op.add_column(
        "daily_practice", sa.Column("practice_hook_title", sa.String(), nullable=False)
    )
    op.add_column(
        "daily_practice",
        sa.Column("practice_hook_question", sa.String(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("daily_practice", "practice_hook_question")
    op.drop_column("daily_practice", "practice_hook_title")
    op.drop_column("daily_practice", "practice_intro")
    op.drop_column("daily_practice", "practice_title")
    # ### end Alembic commands ###
