"""Add composite pk to PointArticleConcept

Revision ID: 07e88ab50c98
Revises: 63af7264fba3
Create Date: 2024-11-05 15:17:58.527541

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "07e88ab50c98"
down_revision: Union[str, None] = "63af7264fba3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Manually added
    op.drop_constraint(
        "point_article_concept_pkey", "point_article_concept", type_="primary"
    )

    # Add a new primary key constraint with the three columns
    op.create_primary_key(
        "point_article_concept_pkey",
        "point_article_concept",
        ["article_id", "concept_id", "point_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Manually added
    op.drop_constraint(
        "point_article_concept_pkey", "point_article_concept", type_="primary"
    )
    op.create_primary_key(
        "point_article_concept_pkey", "point_article_concept", ["point_id"]
    )
    # ### end Alembic commands ###
