"""Add pointarticleconcept and commentarticleconcept tables

Revision ID: 125e6db5e654
Revises: e85f0a7f8e17
Create Date: 2024-10-23 16:36:51.638712

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "125e6db5e654"
down_revision: Union[str, None] = "e85f0a7f8e17"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comment_article_concept",
        sa.Column("comment_id", sa.Integer(), nullable=False),
        sa.Column("skill_issue", sa.String(), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("concept_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["article_id", "concept_id"],
            ["article_concept.article_id", "article_concept.concept_id"],
        ),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["comment.id"],
        ),
        sa.PrimaryKeyConstraint("comment_id"),
    )
    op.create_table(
        "point_article_concept",
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("concept_id", sa.Integer(), nullable=False),
        sa.Column("point_id", sa.Integer(), nullable=False),
        sa.Column("elaboration", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["article_id", "concept_id"],
            ["article_concept.article_id", "article_concept.concept_id"],
        ),
        sa.ForeignKeyConstraint(
            ["point_id"],
            ["point.id"],
        ),
        sa.PrimaryKeyConstraint("point_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("point_article_concept")
    op.drop_table("comment_article_concept")
    # ### end Alembic commands ###
