"""Add image_url column

Revision ID: 22cde3c77a60
Revises: 89c55f5d7a38
Create Date: 2024-11-09 20:20:59.303408

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "22cde3c77a60"
down_revision: Union[str, None] = "89c55f5d7a38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("image_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "image_url")
    # ### end Alembic commands ###
