"""Add useless column to article

Revision ID: 288fe35bd99f
Revises: 7e94c7b5ee8d
Create Date: 2024-10-17 22:27:11.571688

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "288fe35bd99f"
down_revision: Union[str, None] = "7e94c7b5ee8d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "article",
        sa.Column("useless", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("article", "useless")
    # ### end Alembic commands ###
