"""Adjust note table

Revision ID: 32880cfa515b
Revises: b50da2b8e07b
Create Date: 2024-10-03 17:58:34.961611

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "32880cfa515b"
down_revision: Union[str, None] = "b50da2b8e07b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("note", sa.Column("category_id", sa.Integer(), nullable=True))
    op.alter_column("note", "start_index", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("note", "end_index", existing_type=sa.INTEGER(), nullable=True)
    op.create_foreign_key(None, "note", "category", ["category_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "note", type_="foreignkey")
    op.alter_column("note", "end_index", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("note", "start_index", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("note", "category_id")
    # ### end Alembic commands ###
