"""Add submission id field

Revision ID: 3475486ebd66
Revises: 32880cfa515b
Create Date: 2024-10-07 14:24:48.860652

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3475486ebd66"
down_revision: Union[str, None] = "32880cfa515b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("like", "analysis_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("like", "analysis_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
