"""Add comment text

Revision ID: 381abba9e9bc
Revises: b47a225ff91c
Create Date: 2024-10-09 19:00:48.315533

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "381abba9e9bc"
down_revision: Union[str, None] = "b47a225ff91c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comment", sa.Column("content", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("comment", "content")
    # ### end Alembic commands ###
