"""Add deleted_at datetime column

Revision ID: 59cef91d2fa1
Revises: e75763c6e323
Create Date: 2024-10-30 01:11:48.375503

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "59cef91d2fa1"
down_revision: Union[str, None] = "e75763c6e323"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("analysis", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column("answer", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column("article", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column(
        "article_bookmark", sa.Column("deleted_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "article_concept", sa.Column("deleted_at", sa.DateTime(), nullable=True)
    )
    op.add_column("bookmark", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column("category", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column("comment", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column(
        "comment_analysis", sa.Column("deleted_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "comment_article_concept", sa.Column("deleted_at", sa.DateTime(), nullable=True)
    )
    op.add_column("concept", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column("essay", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column("event", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column("fallback", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column("gp_question", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column(
        "gp_question_categories", sa.Column("deleted_at", sa.DateTime(), nullable=True)
    )
    op.add_column("like", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column("note", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column("paragraph", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column(
        "password-reset", sa.Column("deleted_at", sa.DateTime(), nullable=True)
    )
    op.add_column("point", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column(
        "point_analysis", sa.Column("deleted_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "point_article_concept", sa.Column("deleted_at", sa.DateTime(), nullable=True)
    )
    op.add_column("stripe_price", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column(
        "stripe_product", sa.Column("deleted_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "stripe_session", sa.Column("deleted_at", sa.DateTime(), nullable=True)
    )
    op.add_column("subscription", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column("tier", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column(
        "top_article_group", sa.Column("deleted_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "top_article_group_article",
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
    )
    op.add_column("usage", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column("user", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column(
        "user_question", sa.Column("deleted_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "user_read_article", sa.Column("deleted_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "user_read_event", sa.Column("deleted_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_read_event", "deleted_at")
    op.drop_column("user_read_article", "deleted_at")
    op.drop_column("user_question", "deleted_at")
    op.drop_column("user", "deleted_at")
    op.drop_column("usage", "deleted_at")
    op.drop_column("top_article_group_article", "deleted_at")
    op.drop_column("top_article_group", "deleted_at")
    op.drop_column("tier", "deleted_at")
    op.drop_column("subscription", "deleted_at")
    op.drop_column("stripe_session", "deleted_at")
    op.drop_column("stripe_product", "deleted_at")
    op.drop_column("stripe_price", "deleted_at")
    op.drop_column("point_article_concept", "deleted_at")
    op.drop_column("point_analysis", "deleted_at")
    op.drop_column("point", "deleted_at")
    op.drop_column("password-reset", "deleted_at")
    op.drop_column("paragraph", "deleted_at")
    op.drop_column("note", "deleted_at")
    op.drop_column("like", "deleted_at")
    op.drop_column("gp_question_categories", "deleted_at")
    op.drop_column("gp_question", "deleted_at")
    op.drop_column("fallback", "deleted_at")
    op.drop_column("event", "deleted_at")
    op.drop_column("essay", "deleted_at")
    op.drop_column("concept", "deleted_at")
    op.drop_column("comment_article_concept", "deleted_at")
    op.drop_column("comment_analysis", "deleted_at")
    op.drop_column("comment", "deleted_at")
    op.drop_column("category", "deleted_at")
    op.drop_column("bookmark", "deleted_at")
    op.drop_column("article_concept", "deleted_at")
    op.drop_column("article_bookmark", "deleted_at")
    op.drop_column("article", "deleted_at")
    op.drop_column("answer", "deleted_at")
    op.drop_column("analysis", "deleted_at")
    # ### end Alembic commands ###
