"""Update subscription table

Revision ID: 5d5b472013f6
Revises: 933d84ad4302
Create Date: 2024-10-20 22:03:21.508656

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5d5b472013f6"
down_revision: Union[str, None] = "933d84ad4302"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "subscription",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "subscription", "user_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "subscription", "user_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "subscription",
        "id",
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        postgresql_using="id::integer",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
