"""Add essay rate limit

Revision ID: 63af7264fba3
Revises: 4f9ec96fc98e
Create Date: 2024-10-31 14:54:32.307467

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy.orm as orm
from src.limits.models import Tier


# revision identifiers, used by Alembic.
revision: str = "63af7264fba3"
down_revision: Union[str, None] = "4f9ec96fc98e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

ESSAY_LIMITS = {"Free": 3, "Premium": 10, "Unverified": 0, "Admin": 1000}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tier",
        sa.Column("essay_limit", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "usage", sa.Column("essays", sa.Integer(), server_default="0", nullable=False)
    )
    session = orm.Session(bind=op.get_bind())
    for tier_type, essay_limit in ESSAY_LIMITS.items():
        tier = session.scalar(sa.select(Tier).where(Tier.label == tier_type))
        tier.essay_limit = essay_limit
        session.add(tier)
    session.commit()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usage", "essays")
    op.drop_column("tier", "essay_limit")
    # ### end Alembic commands ###
