"""Add fallback table

Revision ID: 65b186bae301
Revises: c1022b3f1de5
Create Date: 2024-09-27 01:37:55.705475

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "65b186bae301"
down_revision: Union[str, None] = "c1022b3f1de5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fallback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("point_id", sa.Integer(), nullable=False),
        sa.Column("alt_approach", sa.String(), nullable=False),
        sa.Column("general_argument", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["point_id"],
            ["point.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fallback")
    # ### end Alembic commands ###
