"""create user table

Revision ID: 681607ac9aeb
Revises:
Create Date: 2024-09-21 13:12:29.755835

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "681607ac9aeb"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("NORMAL", "GOOGLE", name="accounttype").create(op.get_bind())
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column(
            "account_type",
            postgresql.ENUM("NORMAL", "GOOGLE", name="accounttype", create_type=False),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    sa.Enum("NORMAL", "GOOGLE", name="accounttype").drop(op.get_bind())
    # ### end Alembic commands ###
