"""empty message

Revision ID: 6ab4eae29c9f
Revises: b4a58ef20d2e
Create Date: 2024-10-20 20:42:06.679948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ab4eae29c9f'
down_revision: Union[str, None] = 'b4a58ef20d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('subscription_id_seq'::regclass)"))
    op.drop_constraint('user_subscription_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'subscription_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('subscription_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_subscription_id_fkey', 'user', 'subscription', ['subscription_id'], ['id'])
    op.alter_column('subscription', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('subscription_id_seq'::regclass)"))
    # ### end Alembic commands ###
