"""Join point with analysis instead of event

Revision ID: 6ed8b19e393d
Revises: 3c473e77f83a
Create Date: 2024-09-25 19:29:22.822155

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6ed8b19e393d"
down_revision: Union[str, None] = "3c473e77f83a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "point_analysis",
        sa.Column("analysis_id", sa.Integer(), nullable=False),
        sa.Column("point_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analysis.id"],
        ),
        sa.ForeignKeyConstraint(
            ["point_id"],
            ["point.id"],
        ),
        sa.PrimaryKeyConstraint("analysis_id", "point_id"),
    )
    op.drop_table("point_note")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "point_note",
        sa.Column("event_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("note_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["event.id"], name="point_note_event_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["note_id"], ["point.id"], name="point_note_note_id_fkey"
        ),
        sa.PrimaryKeyConstraint("event_id", "note_id", name="point_note_pkey"),
    )
    op.drop_table("point_analysis")
    # ### end Alembic commands ###
