"""add_top_events_period_to_user

Revision ID: 7f60f0211af1
Revises: feeb1c78c0a2
Create Date: 2024-09-26 21:57:33.021370

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7f60f0211af1"
down_revision: Union[str, None] = "feeb1c78c0a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "top_events_period", sa.Integer(), nullable=False, server_default="7"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "top_events_period")
    # ### end Alembic commands ###
