"""Add Analysis table

Revision ID: 8912e0e896bf
Revises: ff5af4d7ce04
Create Date: 2024-09-22 18:29:26.096419

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8912e0e896bf"
down_revision: Union[str, None] = "ff5af4d7ce04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["event.id"],
        ),
        sa.PrimaryKeyConstraint("event_id", "category_id"),
    )
    op.drop_table("event_category")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_category",
        sa.Column("event_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("category_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"], ["category.id"], name="event_category_category_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["event.id"], name="event_category_event_id_fkey"
        ),
        sa.PrimaryKeyConstraint("event_id", "category_id", name="event_category_pkey"),
    )
    op.drop_table("analysis")
    # ### end Alembic commands ###
