"""Add example generated column

Revision ID: 89c55f5d7a38
Revises: 68edf299d1c3
Create Date: 2024-11-07 04:02:09.851723

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "89c55f5d7a38"
down_revision: Union[str, None] = "68edf299d1c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "point",
        sa.Column(
            "example_regenerated", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("point", "example_regenerated")
    # ### end Alembic commands ###
