"""Add GP Questions tables

Revision ID: 8c458d0adb18
Revises: 8912e0e896bf
Create Date: 2024-09-22 18:49:41.011371

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8c458d0adb18"
down_revision: Union[str, None] = "8912e0e896bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gp_question",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question", sa.String(), nullable=False),
        sa.Column("is_llm_generated", sa.Boolean(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["event.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "gp_question_categories",
        sa.Column("gp_question_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
        ),
        sa.ForeignKeyConstraint(
            ["gp_question_id"],
            ["gp_question.id"],
        ),
        sa.PrimaryKeyConstraint("gp_question_id", "category_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gp_question_categories")
    op.drop_table("gp_question")
    # ### end Alembic commands ###
