"""Add id to analysis

Revision ID: 90baf2b50ff3
Revises: bc5fcbe47713
Create Date: 2024-09-23 00:55:33.251027

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "90baf2b50ff3"
down_revision: Union[str, None] = "bc5fcbe47713"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    (op.add_column("analysis", sa.Column("id", sa.Integer(), nullable=False)),)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analysis", "id")
    # ### end Alembic commands ###
