"""Add elaboration for third layer

Revision ID: 951ac4411b0d
Revises: feeb1c78c0a2
Create Date: 2024-09-26 21:39:24.431100

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "951ac4411b0d"
down_revision: Union[str, None] = "feeb1c78c0a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("point", sa.Column("positive", sa.Boolean(), nullable=False))
    op.add_column(
        "point_analysis", sa.Column("elaboration", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("point_analysis", "elaboration")
    op.drop_column("point", "positive")
    # ### end Alembic commands ###
