"""Add email verification used column

Revision ID: b6ac4d92ff23
Revises: 9940d8ca67a4
Create Date: 2024-10-30 20:27:30.163157

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b6ac4d92ff23"
down_revision: Union[str, None] = "9940d8ca67a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("email_verification", sa.Column("used", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("email_verification", "used")
    # ### end Alembic commands ###
