"""Add image url to article

Revision ID: b8f3f95c78b6
Revises: 8c458d0adb18
Create Date: 2024-09-22 18:56:47.024304

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b8f3f95c78b6"
down_revision: Union[str, None] = "8c458d0adb18"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("article", sa.Column("image_url", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("article", "image_url")
    # ### end Alembic commands ###
