"""Remove analysis field from event

Revision ID: bc5fcbe47713
Revises: f624d58d3f42
Create Date: 2024-09-22 22:33:38.823000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bc5fcbe47713"
down_revision: Union[str, None] = "f624d58d3f42"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("event", "analysis")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "event",
        sa.Column("analysis", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
