"""add_concept_like

Revision ID: c54110455094
Revises: 61b03cca7e85
Create Date: 2024-10-26 19:22:42.470241

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c54110455094"
down_revision: Union[str, None] = "61b03cca7e85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("like", sa.Column("concept_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "like", "concept", ["concept_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "like", type_="foreignkey")
    op.drop_column("like", "concept_id")
    # ### end Alembic commands ###
