"""Add second parent_id column to note

Revision ID: cd2e365bd294
Revises: c54110455094
Create Date: 2024-10-27 10:52:51.319456

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cd2e365bd294"
down_revision: Union[str, None] = "c54110455094"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("note", sa.Column("parent_id_two", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("note", "parent_id_two")
    # ### end Alembic commands ###
