"""Add rating to event

Revision ID: d369cd69a23b
Revises: b8f3f95c78b6
Create Date: 2024-09-22 18:59:11.283743

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d369cd69a23b"
down_revision: Union[str, None] = "b8f3f95c78b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("event", sa.Column("rating", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("event", "rating")
    # ### end Alembic commands ###
