"""Add columns to event table

Revision ID: e84e13568072
Revises: 423a1e6552f0
Create Date: 2024-09-21 17:21:24.515814

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e84e13568072"
down_revision: Union[str, None] = "423a1e6552f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("event", sa.Column("is_singapore", sa.Boolean(), nullable=False))
    op.add_column(
        "event", sa.Column("original_article_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "event", "article", ["original_article_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "event", type_="foreignkey")
    op.drop_column("event", "original_article_id")
    op.drop_column("event", "is_singapore")
    # ### end Alembic commands ###
