"""Rename article_id column

Revision ID: e85f0a7f8e17
Revises: bb469691eed3
Create Date: 2024-10-23 14:43:06.884530

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e85f0a7f8e17"
down_revision: Union[str, None] = "bb469691eed3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_read_article", sa.Column("article_id", sa.Integer(), nullable=False)
    )
    op.drop_constraint(
        "user_read_article_event_id_fkey", "user_read_article", type_="foreignkey"
    )
    op.create_foreign_key(None, "user_read_article", "article", ["article_id"], ["id"])
    op.drop_column("user_read_article", "event_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_read_article",
        sa.Column("event_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "user_read_article", type_="foreignkey")
    op.create_foreign_key(
        "user_read_article_event_id_fkey",
        "user_read_article",
        "article",
        ["event_id"],
        ["id"],
    )
    op.drop_column("user_read_article", "article_id")
    # ### end Alembic commands ###
