"""Add article group models


Revision ID: ed7688df4af4
Revises: 288fe35bd99f
Create Date: 2024-10-18 21:17:47.970426

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ed7688df4af4"
down_revision: Union[str, None] = "288fe35bd99f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("NORMAL", "ADMIN", name="role").create(op.get_bind())
    op.create_table(
        "top_event_group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("singapore_only", sa.Boolean(), nullable=False),
        sa.Column("published", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "top_event_group_event",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("top_event_group", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["event.id"],
        ),
        sa.ForeignKeyConstraint(
            ["top_event_group"],
            ["top_event_group.id"],
        ),
        sa.PrimaryKeyConstraint("event_id", "top_event_group"),
    )
    op.add_column(
        "user",
        sa.Column(
            "role",
            postgresql.ENUM("NORMAL", "ADMIN", name="role", create_type=False),
            server_default="NORMAL",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "role")
    op.drop_table("top_event_group_event")
    op.drop_table("top_event_group")
    sa.Enum("NORMAL", "ADMIN", name="role").drop(op.get_bind())
    # ### end Alembic commands ###
