"""Add daily practice models

Revision ID: f00f005a98ec
Revises: 22cde3c77a60
Create Date: 2024-11-12 22:52:02.816344

"""

from typing import Sequence, Union

from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "f00f005a98ec"
down_revision: Union[str, None] = "22cde3c77a60"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "commentparenttype",
        ["ESSAY", "PARAGRAPH", "DAILY_PRACTICE_ATTEMPT"],
        [
            TableReference(
                table_schema="public", table_name="comment", column_name="parent_type"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "commentparenttype",
        ["ESSAY", "PARAGRAPH"],
        [
            TableReference(
                table_schema="public", table_name="comment", column_name="parent_type"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
