"""Add articleconcept id columns to like

Revision ID: f1dc8d2f4fc1
Revises: cd2e365bd294
Create Date: 2024-10-27 11:24:46.110336

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f1dc8d2f4fc1"
down_revision: Union[str, None] = "cd2e365bd294"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("like", sa.Column("article_id", sa.Integer(), nullable=True))
    op.drop_constraint("like_concept_id_fkey", "like", type_="foreignkey")
    op.create_foreign_key(
        None,
        "like",
        "article_concept",
        ["article_id", "concept_id"],
        ["article_id", "concept_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "like", type_="foreignkey")
    op.create_foreign_key(
        "like_concept_id_fkey", "like", "concept", ["concept_id"], ["id"]
    )
    op.drop_column("like", "article_id")
    # ### end Alembic commands ###
