"""Add article date column

Revision ID: f3e847c3ee9d
Revises: e84e13568072
Create Date: 2024-09-21 18:25:05.912853

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f3e847c3ee9d"
down_revision: Union[str, None] = "e84e13568072"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("article", sa.Column("date", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("article", "date")
    # ### end Alembic commands ###
