"""Add user id to note

Revision ID: f624d58d3f42
Revises: 680d9bea2168
Create Date: 2024-09-22 22:29:21.220643

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f624d58d3f42"
down_revision: Union[str, None] = "680d9bea2168"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("note", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "note", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "note", type_="foreignkey")
    op.drop_column("note", "user_id")
    # ### end Alembic commands ###
