"""Change TopEventGroup to TopArticleGroup

Revision ID: fe06c24f397a
Revises: 4da1d4590481
Create Date: 2024-10-23 17:01:25.153346

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fe06c24f397a"
down_revision: Union[str, None] = "4da1d4590481"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "top_article_group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("singapore_only", sa.Boolean(), nullable=False),
        sa.Column("published", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "top_article_group_article",
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("top_article_group", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["article.id"],
        ),
        sa.ForeignKeyConstraint(
            ["top_article_group"],
            ["top_article_group.id"],
        ),
        sa.PrimaryKeyConstraint("article_id", "top_article_group"),
    )
    op.drop_table("top_event_group_event")
    op.drop_table("top_event_group")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "top_event_group_event",
        sa.Column("event_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("top_event_group", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["event.id"], name="top_event_group_event_event_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["top_event_group"],
            ["top_event_group.id"],
            name="top_event_group_event_top_event_group_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "event_id", "top_event_group", name="top_event_group_event_pkey"
        ),
    )
    op.create_table(
        "top_event_group",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("singapore_only", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "published",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="top_event_group_pkey"),
    )
    op.drop_table("top_article_group_article")
    op.drop_table("top_article_group")
    # ### end Alembic commands ###
