"""Add likes table

Revision ID: feeb1c78c0a2
Revises: 6ed8b19e393d
Create Date: 2024-09-25 23:55:17.029650

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "feeb1c78c0a2"
down_revision: Union[str, None] = "6ed8b19e393d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("LIKE", "DISLIKE", name="liketype").create(op.get_bind())
    op.create_table(
        "like",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("point_id", sa.Integer(), nullable=True),
        sa.Column("analysis_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM("LIKE", "DISLIKE", name="liketype", create_type=False),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analysis.id"],
        ),
        sa.ForeignKeyConstraint(
            ["point_id"],
            ["point.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("like")
    sa.Enum("LIKE", "DISLIKE", name="liketype").drop(op.get_bind())
    # ### end Alembic commands ###
