name: CI
on: push
jobs:
  frontend:
    name: frontend (eslint)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: install
        run: npm install
      - name: ESLint
        run: npm run lint
  backend:
    name: format, lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          version: "0.4.10"
      - name: Set up Python
        run: uv python install
      - name: Install dependencies
        run: uv sync --all-extras --dev
      - name: Check code formatting
        run: uvx ruff format --check
      - name: Lint
        run: uvx ruff check
